const path = {
    PUBLIC: '/',
    HOME: '',
    ALL: '*',
    LOGIN: 'login',
    REGISTER: 'register',
    PRODUCTS: 'products',
    PRODUCTS_FILTER: 'products_filter',
    BLOGS: 'blog',
    OUR_SERVICES: 'out-services',
    QRQS: 'qrqs',
    CART: 'cart',
    PRIVATE: 'private',
    LIST_USERS: 'list-users',
    LIST_PRODUCTS: 'list-products',
    PRODUCT_ADD: 'product-add',
    ADD_SYS_USER: 'add-system-user',
    ADD_BRAND: 'add-brand',
    ADD_CATEGORY: 'add-category',
    LIST_CATEGORY: 'list-category',
    LIST_USERS_ADMIN: 'list-users-admin',
    LIST_USERS_BLOCK: 'list-users-block',
    LIST_BRAND: 'list-brand',
    ORDER: 'order',
    ORDER_INCOMPLETE: 'order-incomplete',
    ORDER_COMPLETE: 'order-complete',
    ORDER_CANCELLED: 'order-cancelled',
    LIST_REVOKED: 'list-revoked',
    CHART: 'chart',
}

export default path;